version: "3"
services:
  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file: .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "8080:8080"
    env_file: .env
